services:
  dev:
    build:
      dockerfile: ./Dockerfile
    container_name: actuator_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./:/workspace
    command: tail -f /dev/null
    restart: unless-stopped
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
      - XDG_DATA_HOME=/workspace/.opencode/share
      - XDG_STATE_HOME=/workspace/.opencode/state
      - XDG_CONFIG_HOME=/workspace/.opencode/config
      - XDG_CACHE_HOME=/workspace/.opencode/cache
