import glob
import os
import shutil
import tempfile

import rosbag2_py
from rclpy.serialization import serialize_message
from std_msgs.msg import Float32


def data_df_to_mcap(df, mcap_file_path: str):
    """
    Convert a pandas DataFrame to a single MCAP file.

    Parameters:
        df (pandas.DataFrame): The input DataFrame to convert.
        mcap_file_path (str): The file path to save the MCAP file.
    """
    if not mcap_file_path.endswith(".mcap"):
        mcap_file_path += ".mcap"

    # Remove existing file if it exists
    if os.path.exists(mcap_file_path):
        os.remove(mcap_file_path)

    temp_dir = tempfile.mkdtemp()
    os.rmdir(temp_dir)
    try:
        writer = rosbag2_py.SequentialWriter()
        writer.open(
            rosbag2_py.StorageOptions(uri=temp_dir, storage_id="mcap"),
            rosbag2_py.ConverterOptions(input_serialization_format="cdr", output_serialization_format="cdr"),
        )

        for topic in df.columns:
            writer.create_topic(
                rosbag2_py.TopicMetadata(name=f"/{topic}", type="std_msgs/msg/Float32", serialization_format="cdr")
            )

        for topic in df.columns:
            for i in range(len(df)):
                msg = Float32()
                msg.data = df.iloc[i][topic]
                timestamp = df.index[i].value
                writer.write(f"/{topic}", serialize_message(msg), timestamp)

        writer.close()

        generated_files = glob.glob(os.path.join(temp_dir, "*.mcap"))
        if not generated_files:
            raise RuntimeError("No MCAP file was generated by rosbag2_py.")

        shutil.move(generated_files[0], mcap_file_path)
    finally:
        shutil.rmtree(temp_dir)
